### ISSUE TITLE
[SMG]-[前端]-Email跳转下一页过慢

### ISSUE THREAD

**Issue by KevinDon** [demonlaiorg/smg#1]
速度太慢

**Comment by KevinDon** [comment]
跳转速度慢得让人忍受不了

**Comment by KevinDon** [comment]
听说慢的让人受不了啊啊啊啊啊

**Comment by zicokuo** [comment]
???


------------------------------------------------------------------
发件人：Kevin Don <notifications@github.com>
发送时间：2019年7月9日(星期二) 16:56
收件人：demonlaiorg/Sale_Message_System <Sale_Message_System@noreply.github.com>
抄　送：Zico郭 <21520993@qq.com>; Assign <assign@noreply.github.com>
主　题：Re: [demonlaiorg/Sale_Message_System] [SMG]-[前端]-Email跳转下一页过慢 (#1)

Closed #1.
